SERVER_BUILD_VERSION ?= 0.0.1
SERVER_BUILD_NAME ?= dev-box-server-$(SERVER_BUILD_VERSION)
SERVER_BOX_NAME ?= $(SERVER_BUILD_NAME).box
SERVER_BOX_PATH ?= box/virtualbox/$(SERVER_BOX_NAME)
SERVER_OVA_NAME ?= $(SERVER_BUILD_NAME).ova
SERVER_OUTPUT_PATH ?= output-dev-box-server
SERVER_OVA_PATH ?= $(SERVER_OUTPUT_PATH)/$(SERVER_OVA_NAME)

DESKTOP_BUILD_VERSION ?= 0.0.1
DESKTOP_BUILD_NAME ?= dev-box-desktop-$(DESKTOP_BUILD_VERSION)
DESKTOP_BOX_NAME ?= $(DESKTOP_BUILD_NAME).box
DESKTOP_BOX_PATH ?= box/virtualbox/$(DESKTOP_BOX_NAME)
DESKTOP_OVA_NAME ?= $(DESKTOP_BUILD_NAME).ova
DESKTOP_OUTPUT_PATH ?= output-dev-box-desktop
DESKTOP_OVA_PATH ?= $(DESKTOP_OUTPUT_PATH)/$(DESKTOP_OVA_NAME)

BUCKET_NAME ?= io-blimp-dev-box

clean:
	rm -rf $(DESKTOP_OUTPUT_PATH) $(SERVER_OUTPUT_PATH)

server:
	packer build server.json

desktop:
	packer build desktop.json

upload/server:
	s3cmd put $(SERVER_BOX_PATH) $(SERVER_OVA_PATH) s3://$(BUCKET_NAME)/

upload/dev-box-desktop:
	s3cmd put $(DESKTOP_BOX_PATH) $(DESKTOP_OVA_PATH) s3://$(BUCKET_NAME)/
