HACKER_BUILD_VERSION ?= 0.0.1
HACKER_BUILD_NAME ?= dev-box-hacker-$(HACKER_BUILD_VERSION)
HACKER_BOX_NAME ?= $(HACKER_BUILD_NAME).box
HACKER_BOX_PATH ?= box/virtualbox/$(HACKER_BOX_NAME)
HACKER_OVA_NAME ?= $(HACKER_BUILD_NAME).ova
HACKER_OUTPUT_PATH ?= output-dev-box-hacker
HACKER_OVA_PATH ?= $(HACKER_OUTPUT_PATH)/$(HACKER_OVA_NAME)

DESKTOP_BUILD_VERSION ?= 0.0.1
DESKTOP_BUILD_NAME ?= dev-box-desktop-$(DESKTOP_BUILD_VERSION)
DESKTOP_BOX_NAME ?= $(DESKTOP_BUILD_NAME).box
DESKTOP_BOX_PATH ?= box/virtualbox/$(DESKTOP_BOX_NAME)
DESKTOP_OVA_NAME ?= $(DESKTOP_BUILD_NAME).ova
DESKTOP_OUTPUT_PATH ?= output-dev-box-desktop
DESKTOP_OVA_PATH ?= $(DESKTOP_OUTPUT_PATH)/$(DESKTOP_OVA_NAME)

BUCKET_NAME ?= io-blimp-dev-box

clean:
	rm -rf $(DESKTOP_OUTPUT_PATH) $(HACKER_OUTPUT_PATH)

hacker:
	packer build hacker.json

desktop:
	packer build desktop.json

upload/hacker:
	s3cmd put $(HACKER_BOX_PATH) $(HACKER_OVA_PATH) s3://$(BUCKET_NAME)/

upload/dev-box-desktop:
	s3cmd put $(DESKTOP_BOX_PATH) $(DESKTOP_OVA_PATH) s3://$(BUCKET_NAME)/
