#!/bin/bash -eux

echo "==> Cleaning up Ubuntu 14.04 Desktop bloat"
apt-get -y purge account-plugin-aim \
    account-plugin-facebook \
    account-plugin-flickr \
    account-plugin-jabber \
    account-plugin-salut \
    account-plugin-twitter \
    account-plugin-windows-live \
    account-plugin-yahoo \
    aisleriot \
    brltty \
    colord \
    deja-dup \
    deja-dup-backend-gvfs \
    duplicity \
    empathy \
    empathy-common \
    evolution-data-server-online-accounts \
    example-content \
    firefox \
    friends \
    friends-dispatcher \
    friends-facebook \
    friends-twitter \
    gnome-accessibility-themes \
    gnome-contacts \
    gnome-mahjongg \
    gnome-mines \
    gnome-orca \
    gnome-screensaver \
    gnome-sudoku \
    gnome-video-effects \
    gnomine \
    landscape-common \
    libfriends0 \
    libfriends0:amd64 \
    libreoffice-avmedia-backend-gstreamer \
    libreoffice-base-core \
    libreoffice-calc \
    libreoffice-common \
    libreoffice-core \
    libreoffice-draw \
    libreoffice-gnome \
    libreoffice-gtk \
    libreoffice-impress \
    libreoffice-math \
    libreoffice-ogltrans \
    libreoffice-pdfimport \
    libreoffice-presentation-minimizer \
    libreoffice-style-galaxy \
    libreoffice-style-human \
    libreoffice-writer \
    libsane \
    libsane-common \
    mcp-account-manager-uoa \
    nautilus-sendto-empathy \
    python3-uno \
    rhythmbox \
    rhythmbox-plugins \
    rhythmbox-plugin-zeitgeist \
    sane-utils \
    shotwell \
    shotwell-common \
    telepathy-gabble \
    telepathy-haze \
    telepathy-idle \
    telepathy-indicator \
    telepathy-logger \
    telepathy-mission-control-5 \
    telepathy-salut \
    thunderbird \
    thunderbird-gnome-support \
    totem \
    totem-common \
    totem-mozilla \
    totem-plugins \
    unity-scope-audacious \
    unity-scope-chromiumbookmarks \
    unity-scope-clementine \
    unity-scope-colourlovers \
    unity-scope-devhelp \
    unity-scope-firefoxbookmarks \
    unity-scope-gdrive \
    unity-scope-gmusicbrowser \
    unity-scope-gourmet \
    unity-scope-guayadeque \
    unity-scope-manpages \
    unity-scope-musicstores \
    unity-scope-musique \
    unity-scope-openclipart \
    unity-scope-texdoc \
    unity-scope-tomboy \
    unity-scope-video-remote \
    unity-scope-virtualbox \
    unity-scope-yelp \
    unity-scope-zotero \

